In [1]:
# importing numpy lib  
import numpy as np

In [2]:
# creating array 
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
#creating array from of 20 element
b=np.arange(20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [44]:
#creating 0 values matrix of (3,4)
z=np.zeros((3,4))# (row,column)
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
#creating 1 values matrix of(4,6)[rows,columns]
o=np.ones((4,6))
print(o)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [6]:
##divides the value equally till the count i.e-5    divide 0,1,in 5 eqal parts
t=np.linspace(0,1,5)
print(t)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
np.logspace(-2.2,5)

array([6.30957344e-03, 8.84990840e-03, 1.24130227e-02, 1.74107038e-02,
       2.44205309e-02, 3.42526264e-02, 4.80432804e-02, 6.73862717e-02,
       9.45170600e-02, 1.32571137e-01, 1.85946392e-01, 2.60811376e-01,
       3.65818198e-01, 5.13102442e-01, 7.19685673e-01, 1.00944261e+00,
       1.41586031e+00, 1.98590827e+00, 2.78546663e+00, 3.90693994e+00,
       5.47993630e+00, 7.68624610e+00, 1.07808514e+01, 1.51213943e+01,
       2.12095089e+01, 2.97487956e+01, 4.17261354e+01, 5.85257434e+01,
       8.20891416e+01, 1.15139540e+02, 1.61496556e+02, 2.26517647e+02,
       3.17717266e+02, 4.45635307e+02, 6.25055193e+02, 8.76712387e+02,
       1.22969078e+03, 1.72478392e+03, 2.41920945e+03, 3.39322177e+03,
       4.75938700e+03, 6.67559216e+03, 9.36329209e+03, 1.31331029e+04,
       1.84206997e+04, 2.58371673e+04, 3.62396232e+04, 5.08302738e+04,
       7.12953531e+04, 1.00000000e+05])

In [46]:
#creating 4 elements array , storing in n  
n=np.arange(4)
print(n)

[0 1 2 3]


In [9]:
#appending 10 in each element of n 
n+10

array([10, 11, 12, 13])

In [47]:
#multiplying each value of n by 2
n*2

array([0, 2, 4, 6])

In [11]:
#multiplying each value of n by 2
n/2

array([0. , 0.5, 1. , 1.5])

In [12]:
#adding each value of n by n itself
n+n

array([0, 2, 4, 6])

In [13]:
# dot function results in multiply the matrix element of same position and addition
n.dot(n)

14

In [14]:
#putting the array in diagonal matrix
x=np.diag(n)
x

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [53]:
# v@v results in the square of the matrix  
v=np.diag(np.arange(4))
print(v@v)

[[0 0 0 0]
 [0 1 0 0]
 [0 0 4 0]
 [0 0 0 9]]


In [16]:
v=np.diag(np.arange(4))
v

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [17]:
x=np.arange(5)
y=np.arange(6,11)
z=np.append(x,y)
print("\n",x)
print("\n",y)
print("\n",z)


 [0 1 2 3 4]

 [ 6  7  8  9 10]

 [ 0  1  2  3  4  6  7  8  9 10]


In [18]:
x=np.array([0,0,0])
y=np.array([1,1,1])
z=np.array([2,2,2])
print(np.hstack((x,y,z)))
print("\n")
print(np.vstack((x,y,z)))


[0 0 0 1 1 1 2 2 2]


[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [19]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a[2]

2

In [21]:
b=np.arange(5,20)
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
b[2:10]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
b[-5]

15

In [24]:
b[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5])

In [25]:
b[-1:0:-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6])

In [26]:
b[2:15:2]

array([ 7,  9, 11, 13, 15, 17, 19])

In [27]:
x=np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
x[0:3,0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [29]:
x[2:3]

array([[ 8,  9, 10, 11]])

In [30]:
x[2,2]

10

In [31]:
x[2:3,3:4]

array([[11]])

In [32]:
x[0:3,0]

array([0, 4, 8])

In [33]:
arr=np.arange(10).reshape(2,5)

In [34]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [35]:
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [36]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [38]:
arr=np.arange(12)
arr.reshape((2,6,-1))

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]])

# ARRAY OPERATION


In [39]:
arr1=np.arange(6).reshape(2,3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
arr2=np.arange(5,11).reshape(2,3)
arr2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [41]:
arr1+arr2

array([[ 5,  7,  9],
       [11, 13, 15]])

In [42]:
arr1*arr2

array([[ 0,  6, 14],
       [24, 36, 50]])

In [55]:
ar=np.arange(12).reshape(2,2,3)
ar

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])